### ISSUE TITLE
forget / forgotten device

### ISSUE THREAD

**Issue by davisford** [WICG/webhid#101]
Hi, I built a fairly simple test app.  I note that when I call forget, if I try to pair again with the same device after it is forgotten, the `open()` call returns an error that the "device is forgotten".

If I refresh the browser the device is paired.  Is this the expected behavior, just curious.  The spec says nothing in the `open` section about what it should do if the state is "forgotten" https://wicg.github.io/webhid/#open-method

**Comment by beaufortfrancois** [comment]
Refreshing the browser should not re-pair your device. Can you share your code by any chance?

**Comment by davisford** [comment]
The steps are:

1. Initiate a pairing with `requestDevice({ filter })`, user selects from dialog an un-paired device, call `open()` on device
2. Call `forget( )` on device and clear reference to device
3. Re-initiate a pairing with `requestDevice({filter})`, select same un-paired device, call `open( )` on device -- returns error on open call indicating the "device is forgotten".  Any other calls on the device return an error.
4. Re-fresh the browser, call `getDevice()` and device is returned as a paired device

**Comment by beaufortfrancois** [comment]
Hey @davisford, I'm able to reproduce your issue.
I've filed https://bugs.chromium.org/p/chromium/issues/detail?id=1364070 and will work on a fix now.

Thank you for your feedback!

**Comment by beaufortfrancois** [comment]
You can follow WIP CL at https://chromium-review.googlesource.com/c/chromium/src/+/3899551

**Comment by beaufortfrancois** [comment]
The [fix](https://chromiumdash.appspot.com/commit/6d90a9c14c0701c8a22dfda3846dab071aaacf52) is in [Chrome Canary](https://www.google.com/chrome/canary/).
@davisford Please give it a try and let me know if that works for you.

**Comment by beaufortfrancois** [comment]
> Thanks! I'll try to test it out

@davisford Did that work for you?

**Comment by beaufortfrancois** [comment]
@davisford (gentle ping)

**Comment by davisford** [comment]
@beaufortfrancois we are all good with the Canary test on my end!  Sorry for the delay.  Thanks for the prompt fix!
