### ISSUE TITLE
hid read/write

### ISSUE THREAD

**Issue by ashishsiddharth** [WICG/webhid#11]
Hi,
I have built a custom hid device using Lufa library. I am using python to blink led using following code:
import hid
ocr=hid.device()
ocr.open(0x3eb, 0x204f)                   
ocr.write([0, 1, 0, 0, 0, 0, 0])      // 1 > to turn led on

but, i wanted to blink led using chrome. saw this library webhid. Hence, how should i proceed??
steps done till now:
1. enabled experimental web platform feature on chrome
2. let device = await navigator.hid.requestDevice({filters:[]});
await device.open();
if (device.opened)
  console.log("Device is open.");

3. now how should i write?? in  order to blink led..

**Comment by nondebug** [comment]
What you have so far looks good:

```
let device = await navigator.hid.requestDevice({filters:[]});
await device.open();
if (device.opened)
  console.log("Device is open.");
```

A minor suggestion, consider providing a vendor/product ID filter so the chooser only displays the LUFA device:

```
let vendorProductFilter = { vendorId: 0x03eb, productId: 0x204f };
let device = await navigator.hid.requestDevice({filters:[vendorProductFilter]});
```

To send an output report to the device:

```
// Set reportId to zero if the device does not use report IDs.
let reportId = 0;
// Create the report buffer.
let reportData = new Uint8Array([1, 0, 0, 0, 0, 0, 0, 0]);
// Send the report.
await device.sendReport(reportId, reportData);
```

To register an input report listener:

```
device.oninputreport = (event) => {
  console.log('Received input report with ID ' + event.reportId + ' from ' + event.device.productName);
  console.log(new Uint8Array(event.data.buffer));
};
```

**Comment by ashishsiddharth** [comment]
thank you... it works :)
where could i get proper documentation

**Comment by ashishsiddharth** [comment]
Hi.. the above code is not working now... earlier it used to work fine
Error which i receive is .. device.open() is not a function...  Has the process changed
chrome version 83

**Comment by nondebug** [comment]
Yes, I made some changes to the API and haven't updated the examples and spec yet. Thanks for the reminder.

Previously, navigator.hid.requestDevice returned a Promise that resolves to a single HIDDevice object, or null for no selection. Now, the requestDevice promise resolves to an array of HIDDevice objects or an empty array for no selection.

The intent with this change is to better support devices that expose multiple HID interfaces from the same physical device. Previously, a device with multiple HID interfaces would appear as separate items in the device chooser, one item per interface. If an application needed to access multiple interfaces from the same device, the app had to request access to each interface separately, opening a new chooser for each interface. This resulted in a poor user experience.

After this change, all HID interfaces originating from the same physical device (USB or Bluetooth) are coalesced into a single chooser item. Selecting that item grants permission for all HID interfaces originating from the device, and the Promise resolves to the list of HIDDevice objects representing those interfaces.

Example:

```
let devices = await navigator.hid.requestDevice({filters:[]});
let device = devices[0];
await device.open();
```

I'll close this issue once I've updated the examples and spec.

Also, to reply to your previous question about report IDs (apologies for missing that):

Report ID is an 8-bit identifier defined by the USB HID specification. HID devices support three types of reports: input, output, and feature. If a device needs to support multiple reports of any of these types, the device can assign separate report IDs for each report. For instance, a device that supports both keyboard and mouse inputs might send keyboard data with report ID 1 and mouse data with report ID 2.

Report IDs are optional, some devices don't use them. For WebHID, pass reportId=0 for devices that don't use report IDs.

See the USB HID spec for more information:

https://www.usb.org/document-library/device-class-definition-hid-111

**Comment by ashishsiddharth** [comment]
Well, Thank you for such a prompt reply..
and for the documentation..

**Comment by reillyeon** [comment]
Can this issue be closed?

**Comment by lover0258020** [comment]
Could you help me this question 
https://stackoverflow.com/questions/76151141/webhid-device-opened-but-oninputreport-listener-is-not-work
