### ISSUE TITLE
Published spec out of date

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/webhid#26]
It seems like https://wicg.github.io/webhid/ does not reflect https://github.com/WICG/webhid/blob/master/index.html
Can we make sure it is updated so that web developers interested in WebHID get the latest version?

@nondebug

**Comment by beaufortfrancois** [comment]
![image](https://user-images.githubusercontent.com/634478/88515512-1cc31580-cfec-11ea-8e91-87e4b64e760b.png)

**Comment by nondebug** [comment]
I couldn't switch the github repo to publish master instead of gh-pages so I've synced gh-pages to the current master.
