### ISSUE TITLE
requestDevice signature mistake in the spec

### ISSUE THREAD

**Issue by gre** [WICG/webhid#3]
```
  Promise<sequence<HIDDevice>> requestDevice(
        HIDDeviceRequestOptions options);
```

should be

```
  Promise<HIDDevice> requestDevice(
        HIDDeviceRequestOptions options);
```

**Comment by reillyeon** [comment]
The `requestDevice` method intentionally returns a `sequence<HIDDevice>` to account for the fact that a single USB device (for example) may include multiple USB functions all implementing the USB HID specification. Logically these are a single device but each has its own HID descriptor and set of supported reports. This specification needs some way of indicating to page that the user has selected this kind of composite device.

My suggestion is to add an additional layer of indirection between `HIDDevice` (which is a single physical device) and `HIDCollectionInfo` called something like `HIDInterface`. A single `HIDDevice` could have multiple `HIDInterface`s but they all share common device properties such as USB vendor and product IDs and strings.

**Comment by gre** [comment]
shouldn't it be named `requestDevices` ?

There is something inconsistent in the IDL vs all resources/implementations, unless I missed something:

- in the current spec as shown in https://wicg.github.io/webhid/ the example seems to indicate that it's a `HIDDevice` and not a `HIDDevice[]`:

```js
let requestButton = document.getElementById('request-hid-device');
requestButton.addEventListener('click', async () => {
  let device;
  try {
    device = await navigator.hid.requestDevice({ filters: [{
        vendorId: 0xABCD,
        productId: 0x1234,
        usagePage: 0x0C,
        usage: 0x01
    }]});
  } catch (error) {
    console.log('No device was selected.');
  }

  if (device !== undefined) {
    console.log('HID: ${device.productName}');
  }
});
```

- current Chrome/Chromium implementation have `requestDevice` returning a single device, not a sequence.

- WebUSB also have a `requestDevice` and it returns a single Device ( https://developer.mozilla.org/en-US/docs/Web/API/USB/requestDevice )

**Comment by reillyeon** [comment]
The Chromium implementation is changing to match the specification in this patch: https://chromium-review.googlesource.com/c/chromium/src/+/1966496

**Comment by gre** [comment]
@reillyeon good to know. thanks.

**Comment by reillyeon** [comment]
I think this issue can be closed.
