### ISSUE TITLE
Origin Trial 0.5% question

### ISSUE THREAD

**Issue by JamesB7** [WICG/webhid#37]
How does the 0.5% usage restriction apply to an origin? For letting people beta test a feature, ought I keep it on my main domain (www.) instead of a subdomain (say, beta.) so that under 0.5% of pages requested are likely to use the origin trial? Or is it 0.5% across the whole web instead of my origin?

**Comment by nondebug** [comment]
It's 0.5% of the whole web, as measured by Chrome Status:

https://www.chromestatus.com/metrics/feature/timeline/popularity/2866

Currently navigator.hid.requestDevice is called on less than 0.0001% of page loads.
