### ISSUE TITLE
Cannot open device returned from requestDevice

### ISSUE THREAD

**Issue by joshberg** [WICG/webhid#4]
I am trying to connect to a USB scale (Mettler Toledo). The USB scale registers itself as an HID device. I am able to select it in the drop down after I execute the requestDevice function. However, when I go to open the device, I get a 'Not supported' error. Here is my code:

```
async Connect() {
        if (this.Vendor === 'Mettler Toledo') {
            this.VENDOR_ID = 0x0EB8;
        }
        try {
            this.device = await navigator.hid.requestDevice({
                filters: [{
                    vendorId: this.VENDOR_ID
                }]
            });
            await this.device.open();
            if (this.device.opened)
                console.log('Device is open.');
            let initReport = new Uint8Array(1);
            initReport[0] = 42;
            this.device.oninputreport = e => {
                console.log(e);
            };
            this.device.sendReport(0x01, initReport).then(() => {
                console.log('Sent initialization packet');
            });
            return true;
        } catch (err) {
            console.log(err.message);
        }
    }
```

It appears that the requestDevice function is returning an empty object:
```
HIDDevice {collections: Array(0), opened: false, productId: 0, productName: "", vendorId: 0, …}
     collections: []
     oninputreport: null
     opened: false
     productId: 0
     productName: ""
     vendorId: 0
     __proto__: HIDDevice
```

I am using the Chrome beta branch. Version 77.0.3865.75. I have the flag Experimental Web Platform features enabled.

**Comment by nondebug** [comment]
Please try again with Chrome 78 or newer, Chrome 77 only had minimal WebHID functionality (pretty much just the device chooser).

Here's the relevant commit that enables sending and receiving reports. This page will update when the commit is available on other channels:

https://chromiumdash.appspot.com/commit/cebcd836b83e1d48db1000b2a5878aa90bc7e88b

If you're on Linux, you'll also need to create a udev rule to make the HID device node writable.

**Comment by joshberg** [comment]
Understood. I downloaded Chrome dev branch. I see it is opening it now. I will experiment more tomorrow and give feedback. Thank you!

**Comment by joshberg** [comment]
Updating to Chrome 78 worked! I still struggled for a while... Turns out that my scale was set up with the wrong configuration. I made an adjustment and now I can see the buffer coming through.
