### ISSUE TITLE
Collection type missing from API

### ISSUE THREAD

**Issue by deadbeef84** [WICG/webhid#43]
Collection type (6.2.2.6 in the USB HID v1.11 specification) appears to be missing in WebHID.

**Comment by nondebug** [comment]
Added to the spec as `HIDCollectionInfo.type`: https://github.com/WICG/webhid/commit/6aa792c509fd4eb0ca2b01bcf522f4f1a41061d6

Relevant implementation crbug: https://crbug.com/1162143
