### ISSUE TITLE
Properties missing from HIDReportItem

### ISSUE THREAD

**Issue by deadbeef84** [WICG/webhid#44]
In the USB spec report items (Input, Output and Feature) include several bit flags in the item value that are missing from `HIDReportItem`.

- Bit 0: Data|Constant - Missing.
- ~Bit 1: Array|Variable~ - Included.
- ~Bit 2:  Absolute|Relative~ - Included.
- Bit 3: No Wrap|Wrap - Missing.
- Bit 4: Linear|Nonlinear - Missing.
- Bit 5: Preferred State|No Preferred - Missing.
- ~Bit 6: No Null|Null State~ - Included.
- Bit 7: Non-volatile|Volatile - Missing.
- Bit 8: Bit Field|Buffered Bytes - Missing.
- Bit 9-31: Reserved.

I think the first bit is crucial if you want to make anything generic, or you wont be able to detect PAD data in the report (your best bet would be missing usage?).

I'm also a bit confused what `isRange` refer to, the WebHID spec doesn't say anything about it.

**Comment by nondebug** [comment]
I've added the missing attributes to the IDL: https://github.com/WICG/webhid/commit/7e839c8d02147a43645438ede6d051014aae393b

Here's the relevant crbug for the Chromium implementation: https://crbug.com/1156954

`isRange` is analogous to the `IsRange` value in Windows' [`HIDP_BUTTON_CAPS`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/hidpi/ns-hidpi-_hidp_button_caps) and [`HIDP_VALUE_CAPS`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/hidpi/ns-hidpi-_hidp_value_caps). If isRange is true, the range of usages for the item is defined by `usageMinimum` and `usageMaximum`; if it's false, the usages are listed in the `usages` array.

I'm working on a rewrite of the spec which will include more detail on each of these attributes.
