### ISSUE TITLE
Max. Buffer size in output reports

### ISSUE THREAD

**Issue by AlvaroKarsz** [WICG/webhid#50]
Hi,

I tried to send a HID report to a device from my Linux machine (Ubuntu 18.04), and any buffer bigger than 16B will leads to:
"Output report buffer too long" error in chrome://device-log/.

Then I tried to send a report to the same device using a Windows 10 machine, and I can send buffers up to 1KB.

There is a way to change the max. value? from browser settings? or OS settings?

Thanks

**Comment by nondebug** [comment]
The maximum report size is determined by the device itself. The device should have a HID report descriptor that describes each report supported by the device and the sizes of each of the fields that make up the report. You can sum up all the fields in each report to compute the report size.

For the Windows implementation in Chromium, we can't read the HID report descriptor so we rely on the information provided by the platform's HID API. Windows only gives us [maximum report sizes](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/hidpi/ns-hidpi-_hidp_caps) for each report type (input/output/feature) but no information on the actual report sizes. On Linux/macOS/ChromeOS we can parse the HID report descriptor to get the exact report sizes.

Have you confirmed that the full 1KB buffer is received by the device? I suspect Windows is truncating the buffer to OutputReportByteLength bytes.
