### ISSUE TITLE
When will WebHID be available?

### ISSUE THREAD

**Issue by JamesB7** [WICG/webhid#56]
The origin trial ended on the 23rd. When roughly will the feature be available generally?  Thank you!

**Comment by nondebug** [comment]
WebHID is default-enabled in Chrome 89 which is currently in Beta and will reach Stable channel soon:

> Stable Release: Tue, Mar 2, 2021
> Stable Release (Chrome OS): Tue, Mar 9, 2021

https://chromiumdash.appspot.com/schedule

You can continue to use WebHID in Chrome 88 by enabling `chrome://flags/#enable-experimental-web-platform-features`
