### ISSUE TITLE
Direct ReadFile/WriteFile support

### ISSUE THREAD

**Issue by thegecko** [WICG/webhid#58]
Does/will the WebHID specification support accessing HID devices via the [Readfile](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile) and [Writefile](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-writefile) APIs?

**Comment by nondebug** [comment]
The specification doesn't suggest which platform API to use (and ideally it shouldn't matter), but the Chromium implementation always uses ReadFile and WriteFile for input and output reports on Windows.

[HidConnectionWin::ReadNextInputReportOnHandle](https://source.chromium.org/chromium/chromium/src/+/master:services/device/hid/hid_connection_win.cc;l=213;drc=c8c03b17be9e15e6c895cf6fc0607ec086e6955b) calls ReadFile to read input reports.
[HidConnectionWin::PlatformWrite](https://source.chromium.org/chromium/chromium/src/+/master:services/device/hid/hid_connection_win.cc;l=137;drc=c8c03b17be9e15e6c895cf6fc0607ec086e6955b) calls WriteFile to write output reports.

Feature reports use IOCTLs.

[HidConnectionWin::PlatformGetFeatureReport](https://source.chromium.org/chromium/chromium/src/+/master:services/device/hid/hid_connection_win.cc;l=163;drc=c8c03b17be9e15e6c895cf6fc0607ec086e6955b) uses IOCTL_HID_GET_FEATURE.
[HidConnectionWin::PlatformSendFeatureReport](https://source.chromium.org/chromium/chromium/src/+/master:services/device/hid/hid_connection_win.cc;l=186;drc=c8c03b17be9e15e6c895cf6fc0607ec086e6955b) uses IOCTL_HID_SET_FEATURE.

**Comment by thegecko** [comment]
Thanks, I couldn't see how reportIDs fit in with porting code which uses the ReadFile/WriteFile approach.

However, I just noticed your comment https://github.com/WICG/webhid/issues/11#issuecomment-650410380

`Report IDs are optional, some devices don't use them. For WebHID, pass reportId=0 for devices that don't use report IDs.`

Which is what I needed, perhaps it's worth mentioning this in the WebHID spec?
