### ISSUE TITLE
Configure automatic publishing to GitHub Pages

### ISSUE THREAD

**Issue by reillyeon** [WICG/webhid#69]
The [W3C spec-prod](https://github.com/w3c/spec-prod) GitHub Action can be configured to automatically render the specification using ReSpec and publish the plan HTML version (without a flash of unstyled content) to a separate gh-pages branch.

See [the Web Serial repository](https://github.com/WICG/serial/blob/main/.github/workflows/pr-push.yml) for an example of how to do this. Note that the current preference is to name this file `auto-publish.yml` instead.

**Comment by nondebug** [comment]
I think this is set up now.
