### ISSUE TITLE
waiting for a confirmation from a device

### ISSUE THREAD

**Issue by redDwarf03** [WICG/webhid#89]
Hello
thank you for your lib and your work!

I use your lib to communicate with ledger Nano S.
i have no problem to send basic command and receive the result directly.

But, in some case, a transaction should be approve on the ledger key by the user before receiving the result.
1) js lib send an APDU (ex: c0e40000)
2) a message appear on the ledger key (ex: would you approve the transaction ?)
3) if yes, the ledger send the result to js lib. If not, blank is return
In this case, the lib don't wait the approval and the result. we get directly blank.
How can I use the webhid lib to waiting a response from the ledger.

Apparently, that's 'sendReport' is concerned.

Thx

**Comment by nondebug** [comment]
(For reference, here's the [Ledger Nano S](https://shop.ledger.com/products/ledger-nano-s) product page.)

Can you share some information about the device? Please visit https://nondebug.github.io/webhid-explorer/ and click Connect to connect to the Ledger device. Then, copy the contents of the Device info textarea and paste them here. (Device info contains device properties and information from the HID report descriptor and does not contain any personally identifying information. Still, double-check to make sure you're comfortable sharing that information.)

Also, can you share your code and a log of HID reports sent/received by your app? It's not clear to me how the device is expected to work or how the observed behavior differs from that expectation.

**Comment by redDwarf03** [comment]
hello.
thank you for your answer.. 
I just find the issue few minutes ago... the device send multi blocks... so I should just concatenate response.
No issue from your lib.
